### ISSUE TITLE
[INSERT EMAIL ADDRESS] into CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by coderbyheart** [softwarecrafters/awesome-software-crafting#2]
The CoC is missing an email address in the [Enforcement section](https://github.com/softwarecrafters/awesome-software-crafting/blob/master/CODE_OF_CONDUCT.md#enforcement).

**Comment by rradczewski** [comment]
Thanks for the heads-up @coderbyheart. About time I add MX forwarding to `softwarecrafters.org` :+1:
